#ifndef NNVIEW_IO_GRAPH_LOADER_H_
#define NNVIEW_IO_GRAPH_LOADER_H_

#include <string>

#include "datatypes.h"

//
// Simple JSON graph loader. Supports JSON graph description generated by
// chainer-trt.
//
namespace nnview {

bool load_json_graph(const std::string &filename, Graph *graph);

}  // namespace nnview

#endif  // NNVIEW_IO_GRAPH_LOADER_H_
