#ifndef NNVIEW_IO_WEIGHT_LOADER_H_
#define NNVIEW_IO_WEIGHT_LOADER_H_

#include <string>

#include "datatypes.h"

//
// Simple weights loader for .weights file generated by chainer-trt.
// Assume datatype is float32
//
// format is:
//
// datasize\n
// size0 size1 ...\n
// <<binary>>
//
namespace nnview {

bool load_weights(const std::string &filename, Tensor *tensor);


} // nnview

#endif // NNVIEW_IO_WEIGHT_LOADER_H_
